/**
 * Supplier Rating Software API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RatingCreateDTO {
  /**
   * Mapped to QUALITAET (1-5), 1 = Poor, 5 = Excellent
   */
  quality: number;
  /**
   * Mapped to GRUND_QUALITAET
   */
  qualityReason: string;
  /**
   * Mapped to KOSTEN (1-5), 1 = Poor, 5 = Excellent
   */
  cost: number;
  /**
   * Mapped to KOSTEN_BEGRUENDUNG
   */
  costReason: string;
  /**
   * Mapped to EINHALTUNG_TERMINE (1-5), 1 = Poor, 5 = Excellent
   */
  reliability: number;
  /**
   * Mapped to EINHALTUNG_TERMINE_GRUND
   */
  reliabilityReason: string;
  /**
   * Mapped to VERFUEGBARKEIT (1-5) 1 = Poor, 5 = Excellent
   */
  availability?: number;
  /**
   * Mapped to VERFUEGBARKEIT_BEGRUENDUNG
   */
  availabilityReason?: string;
  /**
   * Mapped to KOMMENTAR
   */
  ratingComment?: string;
  /**
   * PermID of the order this rating belongs to.
   */
  orderId: string;
}
