/**
 * Supplier Rating Software API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Calculated average values for a supplier based on the 4 criteria and total score.
 */
export interface RatingStats {
  /**
   * Average of QUALITAET
   */
  avgQuality?: number;
  /**
   * Average of KOSTEN
   */
  avgCost?: number;
  /**
   * Average of EINHALTUNG_TERMINE
   */
  avgReliability?: number;
  /**
   * Average of VERFUEGBARKEIT
   */
  avgAvailability?: number;
  /**
   * Average of GESAMTBEWERTUNG
   */
  avgTotal?: number;
  /**
   * Number of ratings included in this calculation
   */
  totalRatingCount?: number;
}
